#!/bin/sh

if [ $# -lt 2 ]; then
    echo "Usage: $0 <IP AWS> <NUMBER OF CLIENTS>"
    exit 1
fi

AWS_HOST=$1

for CLI in `seq 1 $2`; do
    echo "Creating client $CLI"
    ./client_test -h $AWS_HOST -t -b & #2>> log_error 1> /dev/null &
    #sleep .100
done
